# Generated by Django 5.1.3 on 2025-04-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_appointmentreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('cash', 'Cash')], default='card', max_length=20),
        ),
    ]
