# Generated by Django 5.1.3 on 2025-04-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_service_duration_service_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstyle',
            name='perfect_corp_id',
            field=models.CharField(blank=True, help_text='ID of this hairstyle in the Perfect Corp API', max_length=255, null=True),
        ),
    ]
