# Generated by Django 5.1.3 on 2024-11-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0006_receipt_receiptitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='purchased_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='User_Management.receipt'),
        ),
    ]
