# Generated by Django 5.1.3 on 2024-11-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0008_customuser_address_customuser_loyalty_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='discount_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
