# Generated by Django 5.1.3 on 2024-12-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0009_customuser_discount_customuser_discount_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
