# Generated by Django 5.1.3 on 2024-12-01 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0011_customuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='expertise',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='User_Management.servicecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='expertise',
            field=models.ManyToManyField(blank=True, related_name='expert_staff', to='User_Management.service'),
        ),
    ]
