# Generated by Django 5.1.3 on 2024-12-01 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0012_servicecategory_customuser_total_ratings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='rating',
            new_name='average_rating',
        ),
    ]
