# Generated by Django 5.1.3 on 2024-12-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0013_rename_rating_customuser_average_rating'),
        ('services', '0006_remove_service_duration_service_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expertise',
            field=models.ManyToManyField(blank=True, related_name='expert_staff', to='services.service'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
