# Generated by Django 5.1.3 on 2025-04-14 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock_Management', '0001_initial'),
        ('User_Management', '0014_alter_customuser_expertise_delete_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock_Management.product'),
        ),
    ]
