# Generated by Django 5.1.3 on 2025-04-14 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock_Management', '0001_initial'),
        ('User_Management', '0015_alter_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock_Management.product'),
        ),
    ]
