# Generated by Django 5.1.3 on 2025-04-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0017_alter_receiptitem_product_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_earned_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
