# Generated by Django 5.1.3 on 2025-04-22 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0006_remove_service_duration_service_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_type', models.CharField(choices=[('oval', 'Oval'), ('round', 'Round'), ('square', 'Square'), ('heart', 'Heart'), ('diamond', 'Diamond'), ('oblong', 'Oblong')], max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFaceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_width_ratio', models.FloatField(help_text='Width to height ratio of the face')),
                ('jaw_width_ratio', models.FloatField(help_text='Jaw width to face width ratio')),
                ('forehead_width_ratio', models.FloatField(help_text='Forehead width to face width ratio')),
                ('cheekbone_width_ratio', models.FloatField(help_text='Cheekbone width to face width ratio')),
                ('face_image', models.ImageField(upload_to='face_analysis/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('face_shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_tryon.faceshape')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualTryOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='user_photos/')),
                ('result_image', models.ImageField(upload_to='virtual_tryon_results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('face_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtual_tryon.userfaceanalysis')),
                ('hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.hairstyle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HairstyleFaceShapeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_strength', models.IntegerField(default=5, help_text='Rating from 1-10 how well this hairstyle suits this face shape')),
                ('face_shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_hairstyles', to='virtual_tryon.faceshape')),
                ('hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_shape_recommendations', to='services.hairstyle')),
            ],
            options={
                'unique_together': {('hairstyle', 'face_shape')},
            },
        ),
    ]
