# Generated by Django 5.1.3 on 2025-04-22 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_tryon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faceshape',
            old_name='shape_type',
            new_name='name',
        ),
    ]
