# Generated by Django 5.1.3 on 2025-04-07 19:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='cancelled_appointments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='completed_appointments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='date_range_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='date_range_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='json_data',
            field=models.JSONField(blank=True, help_text='Additional report data in JSON format', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='product_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('business', 'Business Overview'), ('sales', 'Sales Analysis'), ('appointments', 'Appointment Analysis'), ('stylists', 'Stylist Performance'), ('customers', 'Customer Analysis'), ('inventory', 'Inventory Analysis'), ('services', 'Services Analysis'), ('custom', 'Custom Report')], default='business', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='service_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_customers', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('average_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loyalty_points_issued', models.IntegerField(default=0)),
                ('discounts_redeemed', models.IntegerField(default=0)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_analytics', to='reporting.report')),
            ],
        ),
        migrations.CreateModel(
            name='HairstyleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hairstyle_name', models.CharField(max_length=100)),
                ('hairstyle_id', models.IntegerField()),
                ('try_on_count', models.IntegerField(default=0)),
                ('booking_count', models.IntegerField(default=0)),
                ('popularity_rank', models.IntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hairstyle_analytics', to='reporting.report')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('quantity_sold', models.IntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_stock', models.IntegerField(default=0)),
                ('popularity_rank', models.IntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_analytics', to='reporting.report')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_id', models.IntegerField()),
                ('booking_count', models.IntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('popularity_rank', models.IntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_analytics', to='reporting.report')),
            ],
        ),
        migrations.CreateModel(
            name='StylistPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointments_count', models.IntegerField(default=0)),
                ('completed_appointments', models.IntegerField(default=0)),
                ('cancelled_appointments', models.IntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_performances', to='reporting.report')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
