# Generated by Django 5.1.3 on 2025-04-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_report_cancelled_appointments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('business', 'Business Overview'), ('sales', 'Sales Analysis'), ('appointments', 'Appointment Analysis'), ('stylists', 'Stylist Performance'), ('customers', 'Customer Analysis'), ('inventory', 'Inventory Analysis'), ('services', 'Services Analysis'), ('system_wide', 'System-Wide Analysis'), ('custom', 'Custom Report')], default='business', max_length=20),
        ),
    ]
